MyProject/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyProject.Controllers
{
    [AdminMod]
    public class AdminController : BaseController
    {
        // GET: Admin
        public ActionResult Index()
        {

            return View();
        }
    }
}

MyProject/Controllers/BaseController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MyProject.BusinessLogic;
using MyProject.BusinessLogic.Interfaces;
using MyProject.Extension;

namespace MyProject.Controllers
{
    public class BaseController : Controller
    {
        private readonly ISession _session;

        public BaseController()
        {
            var bl = new BussinesLogic();
            _session = bl.GetSessionBL();
        }

        public void SessionStatus()
        {
            var apiCookie = Request.Cookies["X-KEY"];
            if (apiCookie != null)
            {
                var profile = _session.GetUserByCookie(apiCookie.Value);
                if (profile != null)
                {
                    System.Web.HttpContext.Current.SetMySessionObject(profile);
                    System.Web.HttpContext.Current.Session["LoginStatus"] = "login";
                }
                else
                {
                    System.Web.HttpContext.Current.Session.Clear();
                    if (ControllerContext.HttpContext.Request.Cookies.AllKeys.Contains("X-KEY"))
                    {
                        var cookie = ControllerContext.HttpContext.Request.Cookies["X-KEY"];
                        if (cookie != null)
                        {
                            cookie.Expires = DateTime.Now.AddDays(-1);
                            ControllerContext.HttpContext.Response.Cookies.Add(cookie);
                        }
                    }

                    System.Web.HttpContext.Current.Session["LoginStatus"] = "logout";
                }
            }
            else
            {
                System.Web.HttpContext.Current.Session["LoginStatus"] = "logout";
            }
        }
    }
}

MyProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyProject.Models;
using MyProject.Extension;

namespace MyProject.Controllers
{
    public class HomeController : BaseController
    {
        // GET: Home
        public ActionResult Index()
        {
            SessionStatus();
            var user = System.Web.HttpContext.Current.GetMySessionObject();
            if (user == null)
            {
                return View();
            }

            UserData u = new UserData
            {
                Username = user.Username
            };
            return View(u);
        }

        public ActionResult Sign_up()
        {
            return View();
        }
        public ActionResult Log_in()
        {
            return View();
        }
        public ActionResult Contact_us()
        {
            return View();
        }
    }
}

MyProject/Controllers/LoginController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using MyProject.BusinessLogic.Interfaces;
using MyProject.BusinessLogic;
using MyProject.Domain.Entities.User;
using MyProject.Models;

namespace MyProject.Controllers
{
    public class LoginController : Controller
    {
        private readonly ISession _session;
        public LoginController()
        {
            var bl = new BussinesLogic();
            _session = bl.GetSessionBL();
        }

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UserLogin login)
        {
            /*
            SessionStatus();
            if ((string)System.Web.HttpContext.Current.Session["LoginStatus"] != "login")
            {
                return RedirectToAction("Index", "Login");
            }
            */

            if (ModelState.IsValid)
            {
                // Mapper.Initialize(cfg => cfg.CreateMap<UserLogin, ULoginData>());
                //var data = Mapper.Map<ULoginData>(login);

                var config = new MapperConfiguration(cfg => {
                    cfg.CreateMap<UserLogin, ULoginData>();
                });

                IMapper mapper = config.CreateMapper();
                var source = new UserLogin();
                var data = mapper.Map<UserLogin, ULoginData>(source);

                data.LoginIp = Request.UserHostAddress;
                data.LoginDateTime = DateTime.Now;

                var userLogin = _session.UserLogin(data);
                if (userLogin.Status)
                {
                    HttpCookie cookie = _session.GenCookie(login.Credential);
                    ControllerContext.HttpContext.Response.Cookies.Add(cookie);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", userLogin.StatusMsg);
                    return View();
                }
            }

            return View();
        
        }

    }
}

MyProject/Controllers/ProductsController.cs
using MyProject.BusinessLogic.DbModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyProject.Controllers
{
    public class ProductsController : Controller
    {
        ProductsContext db = new ProductsContext();
        // GET: Products
        public ViewResult Index()
        {
            return View();
           // return View(db.Products.ToList());
        }
    }
}

MyProject/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using MyProject.BusinessLogic;
using MyProject.BusinessLogic.Interfaces;
using MyProject.Domain.Entities.User;
using MyProject.Models;

namespace MyProject.Controllers
{
    public class RegisterController : Controller
    { 
         private readonly IRegister _register;
         private readonly ISession _session;
            // GET: Login
            public RegisterController()
            {
                var bl = new BusinessLogic.BussinesLogic();
                _register = bl.GetRegisterBL();
                var ss = new BusinessLogic.BussinesLogic();
                _session = ss.GetSessionBL();
            }

            public ActionResult Index()
            {
                return View();
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Index(UsersDbTable user)
            {
                UsersDbTable data = new UsersDbTable
                {
                    Username = user.Username,
                    Email = user.Email,
                    Password = user.Password,
                    
                };

                _register.UserRegisterData(data);

                ULoginData u = new ULoginData
                {
                    Credential = user.Username,
                    Password = user.Password
                };

                _session.UserLogin(u);

                HttpCookie cookie = _session.GenCookie(u.Credential);
                ControllerContext.HttpContext.Response.Cookies.Add(cookie);

                return RedirectToAction("Index", "Home");
            }
        }
    }

MyProject/Views/Admin/Index.cshtml
@using System.Web.Optimization
@model MyProject.Models.Products
@{
    Layout = "~/Views/Shared/_Layout_Blank.cshtml";
    ViewBag.Title = "Admin";
}
<div class="content">
    <div class="float-left"style="margin-top: 100px; margin-left: 200px;">
        <h1>Admin</h1>
        <ul id="update-products">
            <li>
                <div><div class="item">Product ID</div><span></span></div>
                <div><div class="item">Name</div> <input type="text" /></div>
                <div><div class="item">Description</div> <input type="text" /></div>
                <div><div class="item">Price ($)</div> <input type="text" /></div>
                <div><div class="item">Image</div> <input type="image" /></div>
                <div>
                    <input type="button" value="Update" />
                    <input type="button" value="Delete Item" />
                </div>
            </li>
        </ul>
    </div>

    <div class="float-right"style="    margin-top: 100px;margin-right: 400px;" >
        <h2>Add New Product</h2>
        <form id="product">
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>Contact</legend>
                @Html.EditorForModel()
                <p>
                    <input type="submit" value="Save" />
                </p>
            </fieldset>
        </form>
    </div>
</div>

MyProject/Views/Home/Contact_us.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Contact_us";
}
    <div class="body-bg">
        <!-- Default form contact -->
        <form class="text-center border border-light p-5" action="#!" style="width:30%; margin:auto;">

            <p class="h4 mb-4">Contact us</p>

            <!-- Name -->
            <input type="text" id="defaultContactFormName" class="form-control mb-4" placeholder="Name">

            <!-- Email -->
            <input type="email" id="defaultContactFormEmail" class="form-control mb-4" placeholder="E-mail">

            <!-- Subject -->
            <label>Subject</label>
            <select class="browser-default custom-select mb-4">
                <option value="" disabled>Choose option</option>
                <option value="1" selected>Feedback</option>
                <option value="2">Report a bug</option>
                <option value="3">Feature request</option>
                <option value="4">Feature request</option>
            </select>

            <!-- Message -->
            <div class="form-group">
                <textarea class="form-control rounded-0" id="exampleFormControlTextarea2" rows="3" placeholder="Message"></textarea>
            </div>

            <!-- Copy -->
            <div class="custom-control custom-checkbox mb-4">
                <input type="checkbox" class="custom-control-input" id="defaultContactFormCopy">
                <label class="custom-control-label" for="defaultContactFormCopy">Send me a copy of this message</label>
            </div>

            <!-- Send button -->
            <button class="btn btn-info btn-block" type="submit">Send</button>

        </form>
        <!-- Default form contact -->

    </div>

MyProject/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home";
}
@model MyProject.Models.UserData
@using System.Web.Optimization
<main>
    <div id="demo" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
        <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
        </ul>

        <!-- The slideshow -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/Content/themes/base/images/caruseli.jpg" alt="Fruit_1" style="width:100%;">
            </div>
            <div class="carousel-item">
                <img src="~/Content/themes/base/images/caruseli.jpg" alt="Fuit_2" style="width:100%;">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>

    </div>

    <section class="gallery-block cards-gallery">
        <div class="container">
            <div class="heading">
                <h2>Examples of our bonquets</h2>
            </div>
            <div class="row">
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 transform-on-hover">
                        <a class="lightbox" href="../img/image1.jpg">
                            <img src="~/Content/themes/base/images/bucket_1.jpg" alt="Card Image" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h6><a href="#">Bouquet of marshmallows</a></h6>
                            <p class="text-muted card-text">...</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 transform-on-hover">
                        <a class="lightbox" href="../img/image2.jpg">
                            <img src="~/Content/themes/base/images/bucket_2.jpg" alt="Card Image" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h6><a href="#"></a>Bouquet of dried fruits</h6>
                            <p class="text-muted card-text">...</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 transform-on-hover">
                        <a class="lightbox" href="../img/image3.jpg">
                            <img src="~/Content/themes/base/images/bucket_3.jpg" alt="Card Image" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h6><a href="#"></a>Bouquet of nuts</h6>
                            <p class="text-muted card-text">...</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 transform-on-hover">
                        <a class="lightbox" href="../img/image4.jpg">
                            <img src="~/Content/themes/base/images/bucket_4.jpg" alt="Card Image" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h6><a href="#">Bouquet of marshmallows and flowers</a></h6>
                            <p class="text-muted card-text">...</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 transform-on-hover">
                        <a class="lightbox" href="../img/image5.jpg">
                            <img src="~/Content/themes/base/images/bucket_5.jpg" alt="Card Image" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h6><a href="#">Bonquet of oranges</a></h6>
                            <p class="text-muted card-text">...</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 transform-on-hover">
                        <a class="lightbox" href="../img/image6.jpg">
                            <img src="~/Content/themes/base/images/bucket_6.jpg" alt="Card Image" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h6><a href="#">Bouquet of berries</a></h6>
                            <p class="text-muted card-text">...</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</main>

MyProject/Views/Home/Log_in.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Log_in";
}

<div class="text-center body-bg">
    <h1> Login to your account </h1>
    <form style="margin-bottom:200px;">
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

MyProject/Views/Home/Sign_up.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Sign_up";
}
    <div class="body-bg">
        <h2 class="text-center">Sign Up</h2>
        <form class="form-horizontal">
            <div class="form-group">
                <label class="control-label col-xs-3" for="lastName">Last Name:</label>
                <div class="col-xs-9">
                    <input type="text" class="form-control" id="lastName" placeholder="Input last name">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-xs-3" for="firstName">First Name:</label>
                <div class="col-xs-9">
                    <input type="text" class="form-control" id="firstName" placeholder="Input first name">
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-xs-3" for="inputEmail">Email:</label>
                <div class="col-xs-9">
                    <input type="email" class="form-control" id="inputEmail" placeholder="Email">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-xs-3" for="inputPassword">Password:</label>
                <div class="col-xs-9">
                    <input type="password" class="form-control" id="inputPassword" placeholder="Input Password">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-xs-3" for="confirmPassword">Confirm Password:</label>
                <div class="col-xs-9">
                    <input type="password" class="form-control" id="confirmPassword" placeholder="Confirm Password">
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-xs-offset-3 col-xs-9">
                    <label class="checkbox-inline">
                        <input type="checkbox" value="agree">  I agree <a href="#">conditions</a>.
                    </label>
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="col-xs-offset-3 col-xs-9">
                    <input type="submit" class="btn btn-primary" value="Sign Up">
                    <input type="reset" class="btn btn-default" value="Clear Form">
                </div>
            </div>
        </form>
    </div>

MyProject/Views/Login/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Login";
}

@using System.Web.Optimization
@model MyProject.Models.UserLogin

<div class="text-center body-bg">
    <div class="view-header">
        <div class="header-icon">
        </div>
        <div class="header-title">
            <h1>Login to your account</h1>
        </div>
    </div>

    <div class="panel panel-filled">
        <div class="panel-body">
            @Html.ValidationSummary(true)
            @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @id = "LoginForm" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    @Html.LabelFor(m => m.Credential, new { @class = "control-label" })
                    @Html.TextBoxFor(m => m.Credential, new
               {
                   placeholder = "username",
                   title = "Please enter you username",
                   value = "",
                   name = "username",
                   id = "username",
                   @class = "form-control"
               })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "control-label" })
                    @Html.TextBoxFor(m => m.Password, new
               {
                   @class = "form-control",
                   type = "password",
                   title = "Please enter your password",
                   placeholder = "******",
                   value = "",
                   name = "password",
                   id = "password"
               })
                </div>
                <div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            }
        </div>
    </div>

</div>



@section Scripts {
    @Scripts.Render("~/bundles/validation/js")

    <script type="text/javascript">
        $(function () {

            $("#LoginForm").validate({
                rules: {
                    Username: {
                        required: true
                    },
                    Password: {
                        required: true
                    }
                },
                submitHandler: function (form) {
                    form.submit();
                },
                errorPlacement: function (error, element) {
                    $(element)
                        .closest("form")
                        .find("label[for='" + element.attr("id") + "']")
                        .append(error);
                },
                errorElement: "span"
            });
        });


    </script>
}

MyProject/Views/Products/Index.cshtml
@model IEnumerable<MyProject.Models.Products>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Featured Section Begin -->
<section class="featured spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>Featured Product</h2>
                </div>
                <div class="featured__controls">
                    <ul>
                        <li class="active" data-filter="*">All</li>
                        <li data-filter=".fruits">Fruits</li>
                        <li data-filter=".nuts">Nuts</li>
                        <li data-filter=".marshmallows">Marshmallows</li>
                        <li data-filter=".berries">Berries</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row featured__filter">
            <div class="col-lg-3 col-md-4 col-sm-6 mix nuts">
                <div class="featured__item">
                    <div class="featured__item__pic set-bg" data-setbg="">
                        <img src="~/Content/themes/base/images/bucket_7.jpg" />
                        <ul class="featured__item__pic__hover">
                            <li><a href="#"><i class="fas fa-heart"></i></a></li>
                            <li><a href="#"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="featured__item__text">
                        <h6><a href="#">Boquet of Nuts</a></h6>
                        <h5>$3.00</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 mix berries">
                <div class="featured__item">
                    <div class="featured__item__pic set-bg" data-setbg="">
                        <img src="~/Content/themes/base/images/bucket_8.jpg" />
                        <ul class="featured__item__pic__hover">
                            <li><a href="#"><i class="fas fa-heart"></i></a></li>
                            <li><a href="#"><i class="fas fa-shopping-cart "></i></a></li>
                        </ul>
                    </div>
                    <div class="featured__item__text">
                        <h6><a href="#">Bonquet of Strawberry</a></h6>
                        <h5>$3.00</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 mix marshmallows">
                <div class="featured__item">
                    <div class="featured__item__pic set-bg" data-setbg="">
                        <img src="~/Content/themes/base/images/bucket_9.jpg" />
                        <ul class="featured__item__pic__hover">
                            <li><a href="#"><i class="fas fa-heart"></i></a></li>
                            <li><a href="#"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="featured__item__text">
                        <h6><a href="#">Bonquet of Marshmallows</a></h6>
                        <h5>$2.00</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 mix fruits">
                <div class="featured__item">
                    <div class="featured__item__pic set-bg" data-setbg="">
                        <img src="~/Content/themes/base/images/bucket_10.jpg" />
                        <ul class="featured__item__pic__hover">
                            <li><a href="#"><i class="fas fa-heart"></i></a></li>
                            <li><a href="#"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="featured__item__text">
                        <h6><a href="#">Bonquet of Oranges</a></h6>
                        <h5>$3.00</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 mix berries ">
                <div class="featured__item">
                    <div class="featured__item__pic set-bg" data-setbg="">
                        <img src="~/Content/themes/base/images/bucket_11.jpg" />
                        <ul class="featured__item__pic__hover">
                            <li><a href="#"><i class="fas fa-heart"></i></a></li>
                            <li><a href="#"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="featured__item__text">
                        <h6><a href="#">Bonquet of Сherries</a></h6>
                        <h5>$2.00</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 mix *">
                <div class="featured__item">
                    <div class="featured__item__pic set-bg" data-setbg="">
                        <img src="~/Content/themes/base/images/bucket_12.jpg" />
                        <ul class="featured__item__pic__hover">
                            <li><a href="#"><i class="fas fa-heart"></i></a></li>
                            <li><a href="#"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="featured__item__text">
                        <h6><a href="#">Bonquet of Donuts</a></h6>
                        <h5>$3.00</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 mix fruits berries">
                <div class="featured__item">
                    <div class="featured__item__pic set-bg" data-setbg="">
                        <img src="~/Content/themes/base/images/bucket_13.jpg" />
                        <ul class="featured__item__pic__hover">
                            <li><a href="#"><i class="fas fa-heart"></i></a></li>
                            <li><a href="#"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="featured__item__text">
                        <h6><a href="#">Bonquet of Apples and Cherries</a></h6>
                        <h5>$3.00</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 mix fruits ">
                <div class="featured__item">
                    <div class="featured__item__pic set-bg" data-setbg="">
                        <img src="~/Content/themes/base/images/bucket_14.jpg" />
                        <ul class="featured__item__pic__hover">
                            <li><a href="#"><i class="fas fa-heart"></i></a></li>
                            <li><a href="#"><i class="fas fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="featured__item__text">
                        <h6><a href="#">Bonquet of Dried Fruits</a></h6>
                        <h5>$3.00</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Featured Section End -->

MyProject/Views/Shared/View.cshtml
@{
    ViewBag.Title = "View";
}

<h2>View</h2>

MyProject/Views/Shared/_Header.cshtml
@model MyProject.Models.UserData
@{
    ViewBag.Title = "_Header";
}

<div>
    <nav class="navbar navbar-expand-sm bg-warning  navbar-light  fixed-top">
        <a class="navbar-brand" href="#">Logo</a>
        <!-- Links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Home")">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Products")">Shop</a>
            </li>

    
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Contact_us","Home")">Contact Us</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Login")">My Account</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Register")">Sign Up</a>
            </li>
        </ul>

        <form class="form-inline my-2 my-lg-0" style="margin-left:auto">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>
</div>